# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/left_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(301, 238)
        Form.setStyleSheet("QPushButton{\n"
"font: 12pt bold \"Times New Roman\";\n"
"color:rgb(123, 100, 200);\n"
"}\n"
"\n"
"QLabel{\n"
"\n"
"color:rgb(123, 100, 200);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refreshButton = QtWidgets.QPushButton(Form)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_2.addWidget(self.refreshButton)
        self.connectButton = QtWidgets.QPushButton(Form)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_2.addWidget(self.connectButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comPortComboBox = QtWidgets.QComboBox(Form)
        self.comPortComboBox.setObjectName("comPortComboBox")
        self.horizontalLayout.addWidget(self.comPortComboBox)
        self.portComboBox = QtWidgets.QComboBox(Form)
        self.portComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.portComboBox.setObjectName("portComboBox")
        self.portComboBox.addItem("")
        self.portComboBox.addItem("")
        self.horizontalLayout.addWidget(self.portComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.respondLineEdit = QtWidgets.QLineEdit(Form)
        self.respondLineEdit.setEnabled(False)
        self.respondLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.respondLineEdit.setReadOnly(False)
        self.respondLineEdit.setObjectName("respondLineEdit")
        self.verticalLayout.addWidget(self.respondLineEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ethalonButton = QtWidgets.QPushButton(Form)
        self.ethalonButton.setObjectName("ethalonButton")
        self.horizontalLayout_3.addWidget(self.ethalonButton)
        self.singleButton = QtWidgets.QPushButton(Form)
        self.singleButton.setObjectName("singleButton")
        self.horizontalLayout_3.addWidget(self.singleButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startButton = QtWidgets.QPushButton(Form)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_4.addWidget(self.startButton)
        self.multiButton = QtWidgets.QPushButton(Form)
        self.multiButton.setObjectName("myltyButton")
        self.horizontalLayout_4.addWidget(self.multiButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.refreshButton.setText(_translate("Form", "REFRESH"))
        self.connectButton.setText(_translate("Form", "CONNECT"))
        self.portComboBox.setItemText(0, _translate("Form", "115200"))
        self.portComboBox.setItemText(1, _translate("Form", "9600"))
        self.respondLineEdit.setText(_translate("Form", "Disconnect"))
        self.ethalonButton.setText(_translate("Form", "ETHALON"))
        self.singleButton.setText(_translate("Form", "SINGLE"))
        self.startButton.setText(_translate("Form", "START"))
        self.multiButton.setText(_translate("Form", "MULTY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
