# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/rigth_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

try:
    from widget_table import MyTableMain
except ModuleNotFoundError:
    from .widget_table import MyTableMain


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 571)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.isAdminModeCheckButton = QtWidgets.QCheckBox(self.groupBox)
        self.isAdminModeCheckButton.setStyleSheet("")
        self.isAdminModeCheckButton.setObjectName("isAdminModeCheckButton")
        self.verticalLayout_2.addWidget(self.isAdminModeCheckButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.tableWidget = MyTableMain()

        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.saveTableButton = QtWidgets.QPushButton(Form)
        self.saveTableButton.setObjectName("saveTableButton")
        self.horizontalLayout.addWidget(self.saveTableButton)
        self.clearTableButton = QtWidgets.QPushButton(Form)
        self.clearTableButton.setObjectName("clearTableButton")
        self.horizontalLayout.addWidget(self.clearTableButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.importTableButton = QtWidgets.QPushButton(Form)
        self.importTableButton.setObjectName("importTableButton")
        self.horizontalLayout.addWidget(self.importTableButton)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.isAdminModeCheckButton.setText(_translate("Form", "ADMIN MODE"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.importTableButton.setText(_translate("Form", "EXPORT TABLE"))
        self.saveTableButton.setText(_translate("Form", "IMPORT TABLE"))
        self.clearTableButton.setText(_translate("Form", "CLEAR"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
